### ISSUE TITLE
Direct lowering to GCN ISA instead of via ROCM wrapper & dependencies 

### ISSUE THREAD

**Issue by powderluv** [whchung/mlir_roundtrip#6]
I am trying to get this mlir_roundtrip to work on my GFX1030 / BigNavi. Unfortunately ROCM support is missing but with a lot of workarounds (https://github.com/RadeonOpenCompute/ROCm/issues/1390) I have been able to deploy GCN binaries via ROCr on my GFX1030. 

Do you have any examples of this working without the Rocm / Rocblas dependencies ? I am happy to try to plumb that in but wanted to verify if you have something like that before trying it.

**Comment by whchung** [comment]
@powderluv you wanna take a look at:
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir

That's where I do my recent developments.

**Comment by powderluv** [comment]
thank you. closing this out.

**Comment by whchung** [comment]
@powderluv You are welcomed to check some of the end-to-end tests:
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/tree/miopen-dialect/mlir/test/mlir-rocm-runner

Right now host side functions still depends on the existence of HIP runtime.

**Comment by powderluv** [comment]
Thanks for the pointer. that will help. Unfortunately I am unable to get HIP running on gfx1030 with public sources due to this (https://github.com/ROCm-Developer-Tools/HIP/issues/2238) Have you been able to test on gfx10 ? I will debug HIP a little more to see if I can find a workaround then it will be easy to build on your work.

**Comment by whchung** [comment]
@powderluv Unfortunately nope. My focus is on gfx908 target where there is a special matrix multiplication ISA.

We upstreamed those ops some time last year and I was focusing on creating a code generator to use them efficiently.
https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/LLVMIR/ROCDLOps.td#L114

For gfx10 series, @asroy is leading the efforts creating kernels in HIP C++. To my understanding the work is largely done, and hopefully in the next couple ROCm release we'll officially announce gfx10 support. We'll then adopt those insights obtain in C++ and teach MLIR to do the same.

If you monitor some of ROCm repos you should be able to see many gfx10-related stuffs around (eg: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/blob/81d7180b0714be8c14f0cf59d2756f7e5968bd6f/lib/comgr/src/comgr-isa-metadata.def )
